```{r echo=FALSE}
library(tidyverse)

theme_set(theme_classic(base_size = 20)) 
```

#Visualizing multiple regression.
First we explore the data and plot a few associations
```{r echo=FALSE}
smoking=read_csv("smoking_data.csv")

library(skimr)
smoking %>% skim()

library(ggbeeswarm)
smoking %>%
  ggplot(aes(x=smoke,y=lung_capacity))+
  geom_beeswarm()
```

Being exposed to smoking increases lung capacity?
```{r}
smoking %>%
  ggplot(aes(x=age,y=lung_capacity))+
  geom_point()

smoking %>%
  ggplot(aes(x=age,y=lung_capacity,col=smoke))+
  geom_beeswarm()

smoking %>%
  ggplot(aes(x=age,y=lung_capacity,col=smoke))+
  geom_beeswarm()+
  stat_smooth(method="lm")
```

smoking has an negative effect when we control for age. 
```{r}
model1=lm(formula = lung_capacity ~ smoke, data = smoking)

model2=lm(formula = lung_capacity ~ age + smoke, data = smoking)

library(broom)
tidy(model1)
tidy(model2)
```

two ways to visualize this (what's another way?)
```{r}
#1 plot smoking variable vs. residuals of a model excluding smoking
## note that this doesn't always work well for visualization, but at least the x-axis is interpretable
y_given_x1=resid(lm(lung_capacity ~ age, data = smoking))
tibble(smoke=smoking$smoke,y_given_x1=y_given_x1) %>%
  ggplot(aes(x=smoke,y=y_given_x1))+
  geom_beeswarm(alpha=0.1)

#2 partial residuals, this usually works, but the x-axis can sometimes be less interpretable. 
smoking$smoke_integer=as.numeric(as.factor(smoking$smoke))
head(smoking$smoke_integer)
x2_given_x1=resid(lm(smoke_integer ~ age, data = smoking))
y_given_x1=resid(lm(lung_capacity ~ age, data = smoking))

tibble(x2_given_x1,y_given_x1) %>%
  ggplot(aes(x=x2_given_x1,y=y_given_x1))+
  geom_point()+
  stat_smooth(method="lm")

```


